GBCOR-434 setup new nextmatter mock service
tamedia-adtec/gb-poa-nextmatter-mock pull request #1
Opened 2022-09-02 06:52 UTC by EichenbergerLeandro

2022-09-05 06:29 UTC, polster requested changes

2022-09-05 06:29 UTC, polster commented on src/main/java/com/gb/poa/nextmattermock/web/controller/MockController.java
> +                description = "A unique ID of the onboard job to be provided by the caller (used for call-backs).",
Would may be adjust the API description texts a little bit, I guess they come from the nextmatter-api ;-)

2022-09-05 06:29 UTC, polster commented on src/main/java/com/gb/poa/nextmattermock/web/dto/ActionDto.java
> +public record ActionDto (
Optional: Use OpenAPI spec to add some description of the properties + example values.

2022-09-05 06:29 UTC, polster commented on src/main/java/com/gb/poa/nextmattermock/web/controller/MockController.java
> +                                .entity("Job " + jobId + " completed")
I guess this will return a String resp. application/text...would suggest returning JSON

2022-09-05 06:29 UTC, polster commented on src/main/java/com/gb/poa/nextmattermock/web/dto/CompletedStepDto.java
> +    public String toString() {
Cosmetics :-), I guess the toString override can be omitted - resp. if really needed, check if Lombok also offers a class level annotation to generate the method

2022-09-06 06:01 UTC, EichenbergerLeandro commented on src/main/java/com/gb/poa/nextmattermock/web/dto/ActionDto.java
> +public record ActionDto (
OpenApi spec somehow keeps getting ignored/overwritten

2022-09-06 06:09 UTC, EichenbergerLeandro commented on src/main/java/com/gb/poa/nextmattermock/web/dto/CompletedStepDto.java
> +    public String toString() {
removed

2022-09-06 06:27 UTC, EichenbergerLeandro commented on src/main/java/com/gb/poa/nextmattermock/web/controller/MockController.java
> +                                .entity("Job " + jobId + " completed")
done

2022-09-06 08:19 UTC, merged